version: "3.8"

services:
  yolo:
    image: "${IMG_NAME}"
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${S3_BUCKET_NAME_DEV}
      - STORAGE_TYPE=dynamodb
      - POLYBOT_CALLBACK_URL=${POLYBOT_CALLBACK_URL_DEV}
      - YOLO_SQS_QUEUE_URL=${YOLO_SQS_QUEUE_URL_DEV}
      - YOLO_SQS_QUEUE_URL_DEV=${YOLO_SQS_QUEUE_URL_DEV}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL_DEV}
    restart: always


  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otelcol-yolo-dev
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
    command: ["--config=/etc/otelcol/config.yaml"]
    network_mode: host
    restart: always
