version: "3.8"
services:
  yolo:
    image: "${IMG_NAME}"
    ports:
      - "8080:8000"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${S3_BUCKET_NAME}
      - STORAGE_TYPE=${STORAGE_TYPE}
      - POLYBOT_URL=${POLYBOT_URL}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL_PROD}
      - YOLO_SQS_QUEUE_URL_DEV=${YOLO_SQS_QUEUE_URL_PROD}
      - DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}
    restart: always

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otelcol-prod-yolo
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
    command: ["--config=/etc/otelcol/config.yaml"]
    network_mode: host
    restart: always


