services:
  yolo:
    image: "${IMG_NAME}"
    ports:
      - "8080:8000"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${S3_BUCKET_NAME_DEV}
    restart: always

  otelcol:
    image: otel/opentelemetry-collector:latest
    container_name: otelcol-yolo-dev
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-config.yaml
    command: ["--config=/etc/otelcol-config.yaml"]