services:
  yolo:
    image: "${IMG_NAME}"
    ports:
      - "8080:8000"  # Or change to 8443:8080 if needed
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${S3_BUCKET_NAME_PROD}
    restart: always

    image: otel/opentelemetry-collector:latest
    container_name: otelcol-yolo-prod
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-config.yaml
    command: ["--config=/etc/otelcol-config.yaml"]

