name: API Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r torch-requirements.txt
          pip install -r requirements.txt
          pip install pytest  # 👈 Make sure pytest is installed

      - name: Run API tests
        run: python -m pytest tests/test_api.py
