name: Yolo Build Prod

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        id: meta
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/yolo-prod:${{ github.run_number }}
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          docker build -t $IMAGE .
          docker push $IMAGE

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy-prod.yaml
    with:
      image: ${{ needs.Build.outputs.image }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PROD_EC2_HOST: ${{ secrets.PROD_EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET_PROD: ${{ secrets.AWS_S3_BUCKET_PROD }}
